dist: bionic
language: python
python:
  - "3.6"
env:
  - PIPENV_VERBOSITY=-1
virtualenv:
  system_site_packages: true
services:
  - xvfb
addons:
  apt:
    update: true
    packages:
      - python3-gi
      - gir1.2-gtk-3.0
      - gir1.2-glib-2.0
      - libgirepository1.0-dev
      - gir1.2-gnomedesktop-3.0
      - gir1.2-webkit2-4.0
      - gir1.2-notify-0.7
install:
  - pip install --upgrade pip pypresence~=3.3.2 pipenv
  - pipenv install --dev --deploy --ignore-pipfile
script:
  - make check

# Cache the pip dependencies
cache: pip
